<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

/**
 * @var $block \Magento\CatalogInventory\Block\Stockqty\DefaultStockqty
 */
?>
<?php if ($block->isMsgVisible()) : ?>
<?php if($block->getStockQtyLeft()>0) { ?>
    <div class="availability only" title="<?= $block->escapeHtmlAttr(__('Only %1 left', ($block->getStockQtyLeft()))) ?>">
        <?= /* @noEscape */ __('Only %1 remaining', "<strong>{$block->escapeHtml($block->getStockQtyLeft())}</strong>") ?>
    </div>
<?php } ?>
<?php endif ?>
