<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 *
 * @var $block \Magento\Customer\Block\Account\Forgotpassword
 */

// @codingStandardsIgnoreFile

/** @var \Magento\Customer\Block\Account\Forgotpassword $block */
?>
<div class="forget-password-container">
<form class="form password forget"
      action="<?= $block->escapeUrl($block->getUrl('*/*/forgotpasswordpost')) ?>"
      method="post"
      id="form-validate"
      data-mage-init='{"validation":{}}'>
    <fieldset class="fieldset" data-hasrequired="<?= $block->escapeHtmlAttr(__('* Required Fields')) ?>">
        <div class="field note"><?= $block->escapeHtml(__('Enter the e-mail address associated with your account. Click submit to have a password reset link e-mailed to you.')) ?></div>
        <div class="form-headding"><h4><?= $block->escapeHtml(__('Your E-Mail Address')) ?></h4></div>
        <div class="field email required">
            <label for="email_address" class="label"><span><?= $block->escapeHtml(__('E-Mail Address')) ?></span></label>
            <div class="control">
                <div class="loginSpriteRow">
                    <span class="loginSprite mailIcon"><i class="fa fa-envelope" aria-hidden="true"></i></span>
                </div>
                <input type="email" name="email" alt="email" id="email_address" Placeholder="E-Mail Address" class="input-text" value="<?= $block->escapeHtmlAttr($block->getEmailValue()) ?>" data-mage-init='{"mage/trim-input":{}}' data-validate="{required:true, 'validate-email':true}">
            </div>
        </div>
        <?= $block->getChildHtml('form_additional_info') ?>
    </fieldset>
    <div class="actions-toolbar">
        <div class="primary">
            <button type="submit" class="action submit primary"><span><?= $block->escapeHtml(__('Continue')) ?></span></button>
        </div>
        <div class="secondary">
            <a class="action back" href="<?= $block->escapeUrl($block->getLoginUrl()) ?>"><span><?= $block->escapeHtml(__('Back')) ?></span></a>
        </div>
    </div>
</form>
</div>