<!--@subject {{trans "Employee discount code"}} @-->
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>WELCOME TO RAY-BAN</title>
    <style>ul,li{list-style:none;padding:0;margin:0}.table{width:100%}h1{font-size:40px}ul.menulists p a{text-decoration:none;color:#424243;margin:12px 0;display:inline-block}.footer{border-top:3px solid gainsboro;padding-top:20px;display:flex;justify-content:space-between}header{padding:0 45px}a{color:#000}svg{border-radius:20px}a,p,strong,b,span,body{font-family:sans-serif;text-decoration:none}body{width:95%;margin:0 auto}.menulists{margin-top:39%}.menulists li{float:left;text-align:right;margin-left:14px}.font-20{font-size:20px}@media print {body {-webkit-print-color-adjust: exact;}}
    </style>
</head>


<body class="wrapper"  style="padding: -31px;">
    <main>
        <div class="top-menulists">
            <h1><strong>WELCOME TO LEE</strong></h1>
             <p class="font-20"><strong  style="
    text-transform: capitalize;
">Dear {{trans "%customerName," customerName=$customerName}}</strong>
            <p>Welcome your coupon code is {{trans "%couponcodes," couponcodes=$couponcodes}}
            </p>
           
            <p>
            <p>We are happy to have you amongst us.
                <br>
                <br>Got a question? We’re here for you!
                <br>Email us - <strong style="color: black;">customer.care@aceturtle.com</strong> or Call us on 080-46789214</p>
            </div>
    </main>
    <div class="footer-cnter" style="display: flex;justify-content: space-between;margin-top: 2%;border-top: 2px solid  #c7c7c7;">
        <div style=" float: left;width: 50%;">
           <img src="https://www.lee.in/static/frontend/Aceturtle/lee/en_US/images/logo.svg"
             alt="" style="padding: 13px 0 0;width: 21%;"><br>
            <a href="https://lee.in/" style="font-size: larger; color: #222;">lee.in</a>
        </div>
         <div style=" float: right;text-align: right;width: 50%;">
            <ul class="menulists" style="display:inline-flex;margin: 2% auto; margin-right: 35px;margin-top: 17px;">
                <li style="list-style-type: none !important;">
                    <a href="https://www.facebook.com/lee" alt="">  
<img src="https://r3-portal-image.s3-ap-southeast-1.amazonaws.com/templateLogos/facebook-circular-logo.png" alt="">  
                    </a>
                </li>
                <li style="list-style-type: none !important;">
                    <a href="https://twitter.com/Ray_Ban">
                         <img src="https://r3-portal-image.s3-ap-southeast-1.amazonaws.com/templateLogos/twitterimg.png" alt="">
                    </a>
                </li>
                <li style="list-style-type: none !important;">
                    <a href="https://www.instagram.com/lee/">
                         <img src="https://r3-portal-image.s3-ap-southeast-1.amazonaws.com/templateLogos/instagramlog.png" alt="">
                    </a>
                </li>
            </ul>
        </div>
       
           
    </div>
</body>


</html>      

