<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
use Magento\Framework\App\Action\Action;

$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
$productRepository = $objectManager->get('\Magento\Catalog\Model\ProductRepository');
/** @var \Magento\CatalogWidget\Block\Product\ProductsList $block */
?>
<?php if ($exist = ($block->getProductCollection() && $block->getProductCollection()->getSize())) : ?>
    <?php
    $type = 'widget-product-grid';

    $mode = 'grid';

    $image = 'new_products_content_widget_grid';
    $items = $block->getProductCollection()->getItems();

    $showWishlist = true;
    $showCompare = true;
    $showCart = true;
    $templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::SHORT_VIEW;
    $description = false;
    ?>
    <div class="block-new-products <?= /* @noEscape */ $mode ?>">
        <?= /* @noEscape */ '<!-- ' . $image . '-->' ?>
        <div class="products-slider products grid products-grid products-<?= /* @noEscape */ $mode ?> <?= /* @noEscape */ $mode ?>"">
            <ol class="product-items <?= /* @noEscape */ $type ?>">
                <?php $iterator = 1; ?>
                <?php foreach ($items as $_item) : ?>
		      <?php             
                         if($_item->getStyleCode()){
                            try{
                    $parentSku = $_item->getStyleCode() . "_parent";
                    $productObj = $productRepository->get($parentSku);
                    $productUrl = $productObj->getProductUrl();           
                            }catch(\Exception $error){
                                $productUrl = $_item->getProductUrl();
                            }
                         } else{
                            $productUrl = $_item->getProductUrl();
                         }
                    ?>
                    <?= /* @noEscape */ ($iterator++ == 1) ? '<li class="item product product-item">' : '</li><li class=" item product product-item">' ?>
		    <?php if ($showWishlist) :?>
                            <div class="actions-secondary" data-role="add-to-links">
                                <?php if ($this->helper(Magento\Wishlist\Helper\Data::class)->isAllow() && $showWishlist) :?>
                                    <a href="#"
                                       data-post='<?= /* @noEscape */ $block->getAddToWishlistParams($_item) ?>'
                                       class="action towishlist"
                                       data-action="add-to-wishlist"
                                       title="<?= $block->escapeHtmlAttr(__('Add to Wish List')) ?>">
                                        <span><?= $block->escapeHtml(__('Add to Wish List')) ?></span>
                                    </a>
                                <?php endif; ?>
                            </div>
                      <?php endif; ?>
                    <div class="product-item-info">
                        <a href="<?= $block->escapeUrl($productUrl).'?pid='. $_item->getId(); ?>" class="product-item-photo">
                            <?= $block->getImage($_item, $image)->toHtml() ?>
                        </a>
                        <div class="product-item-details">
                            <?= $block->getProductPriceHtml($_item, $type) ?>
                            <strong class="product-item-name">
                                <a title="<?= $block->escapeHtml($_item->getName()) ?>"
                                   href="<?= $block->escapeUrl($productUrl).'?pid='. $_item->getId(); ?>"
                                   class="product-item-link">
                                    <?= $block->escapeHtml($_item->getName()) ?>
                                </a>
                            </strong>
                        </div>
                    </div>
			

                    <?= ($iterator == count($items) + 1) ? '</li>' : '' ?>
                <?php endforeach ?>
            </ol>
        </div>
    </div>
<?php endif;?>
