<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
?>
<?php
/**
 * Template for displaying new products widget
 *
 * @var $block \Magento\Catalog\Block\Product\Widget\NewWidget
 */

// phpcs:disable Magento2.Files.LineLength.MaxExceeded
// phpcs:disable Magento2.Templates.ThisInTemplate.FoundThis
$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
$productRepository = $objectManager->get('\Magento\Catalog\Model\ProductRepository');
if ($exist = ($block->getProductCollection() && $block->getProductCollection()->getSize())) {
    $type = 'widget-new-grid';

    $mode = 'grid';

    $image = 'new_products_content_widget_grid';
    $title = __('New Products');
    $items = $block->getProductCollection()->getItems();

    $showWishlist = true;
    $showCompare = true;
    $showCart = true;
    $templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::DEFAULT_VIEW;
    $description = false;
}
?>

<?php if ($exist) :?>
    <div class="block-new-products <?= /* @noEscape */ $mode ?>">
        <?= /* @noEscape */ '<!-- ' . $image . '-->' ?>
        <div class="products-slider new-products-slider products grid products-grid products-<?= /* @noEscape */ $mode ?> <?= /* @noEscape */ $mode ?>">
            <ol class="product-items <?= /* @noEscape */ $type ?>">
                <?php foreach ($items as $_item) :?>
		  <?php             
                         if($_item->getStyleCode()){
                            try{
                    $parentSku = $_item->getStyleCode() . "_parent";
		    echo "<script>console.log('".$parentSku."');</script>";
                    $productObj = $productRepository->get($parentSku);
                    $productUrl = $productObj->getProductUrl();            
                            }catch(\Exception $error){
                                $productUrl = $_item->getProductUrl();
                            }
                         } else{
                            $productUrl = $_item->getProductUrl();
                         }
                    ?>
                <li class="item product product-item">
                    <div class="product-item-info">
			<!-- < ?= $block->escapeUrl($block->getProductUrl($_item)) ? > -->
                        <a href="<?php echo $productUrl.'?pid='. $_item->getId(); ?>"
                           class="product-item-photo">
                            <?= $block->getImage($_item, $image)->toHtml() ?>
                        </a>
                        <div class="product-item-details">
                            <?= $block->getProductPriceHtml($_item, $type); ?>
                            <strong class="product-item-name">
                                <a title="<?= $block->escapeHtml($_item->getName()) ?>"
                                   href="<?= $block->escapeUrl($productUrl).'?pid='. $_item->getId(); ?>"
                                   class="product-item-link">
                                    <?= $block->escapeHtml($_item->getName()) ?>
                                </a>
                            </strong>
                            <?php /* if ($templateType) :?>
                                <?= $block->getReviewsSummaryHtml($_item, $templateType) ?>
                            <?php endif; */ ?>                            
                        </div>
                    </div>
                 </li>
                <?php endforeach ?>
            </ol>
        </div>
        
    </div>
<?php endif;?>
