<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile
?>
<?php include ($block->getTemplateFile('Aceturtle_Rubicon::order/breadcrum.phtml')); ?>
<?php $_orders = $block->getOrders(); ?>
<?php $orderHelper = $this->helper('Aceturtle\Rubicon\Helper\Order'); ?>
<?= $block->getChildHtml('info') ?>
<?php
// $_objectManager = \Magento\Framework\App\ObjectManager::getInstance();
// $currencysymbol = $_objectManager->get('Magento\Store\Model\StoreManagerInterface');
// $currencyCode = $currencysymbol->getStore()->getCurrentCurrencyCode();
$currencyCode = $orderHelper->getCurrencycode();
$shipmentCount = 0;

$imageHelper = $this->helper(\Magento\Catalog\Helper\Image::class);
$placeholderImageUrl = $imageHelper->getDefaultPlaceholderUrl('image');
?>
<?php if ($_orders && count($_orders)): ?>
    <div class="table-wrapper orders-history">
        <div class="data table table-order-items history" id="my-orders-table">
            <?php foreach ($_orders as $_order): 
            //echo $_order->getRealOrderId(); die();
            ?>
                <?php $_shipments = $orderHelper->getORubiconShipmentData($_order->getRealOrderId()); 
               //print_r($_shipments);die();

		$cancelorders = $this->helper('Aceturtle\Rubicon\Helper\Order')->getCancleorderdata($_order->getRealOrderId()); 
    		$orderData = json_decode($cancelorders, true);

                ?>
                <?php //$_shipments = $orderHelper->getORubiconShipmentData(123456); ?>
                <?php if(!empty($_shipments)) { $shipmentCount++; ?>
                    <?php foreach ($_shipments as $shipment) { 

			if(isset($shipment['_id'])) { $_shipmentId= $shipment['_id'];  } else { $_shipmentId= ""; }
	?>
                        <div class = "my-order-listingpage">
                            <div class="orderhistory-heading">
                                <?php /**<div class="col id"><?= $_order->getRealOrderId() ?></div> **/ ?>
                                <div class="col id"><? // php echo $shipment['shipment_no']; ?><?//php echo $shipment['shipment_no']; ?><p class="ordno"><span>Order No:</span>
                                <span class="orderHistoryHeadingOrderNo"><?php echo $_order->getRealOrderId(); ?></span></p></div>
                                <div class="My-account-Item-viewBtn orderHistoryHeadingBtn">
                                    <button type="button" onclick="location.href='<?php echo $block->getViewUrl($_order)."sid/".$_shipmentId; ?>'"> Order Details </button>
                                </div>
                            </div>
                            <?php if(!empty($shipment['order_items'])) { ?>
                                <?php foreach ($shipment['order_items'] as $items) { 
					$imagePath = $orderHelper->getProductImageUrl($items['sku']);
				?>
                                    <div class="orderhistory-detail">
                                         <div class="order-image">
                                                <img src="<?php if(empty($imagePath)) { echo $placeholderImageUrl; } else { echo $imagePath; } ?>"> 
                                         </div>
                                         <div class="orderHistoryDetailWrapper">
                                            <div class="order-detail">
                                                <?php
                                                if(!empty($items['name'])) { 
						$itemname = preg_replace('\'%20\'', ' ', $items['name']);
						 echo '<p class="productName">'.$itemname.'</p>';  
						}
                                                if(!empty($items['color'])) { echo '<p class="productInfo">'.'Color :'.'<span>'.$items['color'].'</span>'.'</p>'; }
                                                if(!empty($items['size'])) { echo '<p class="productInfo">'.'Size :'.'<span>'.$items['size'].'</span>'.'</p>'; }
                                                if(!empty($items['qty_ordered'])) { echo '<p class="productInfo">'.'Qty :'.'<span>'.$items['qty_ordered'].'</span>'.'</p>'; }
                                                if(!empty($items['pricing_details']['grand_total'])) { echo '<p class="productPrice">'.'Total: '.'₹ '.$items['pricing_details']['grand_total'].'</p>'; }
                                                if(!empty($items['pricing_details']['grand_total'])) { echo  '<p class="productPrice">'.'MRP: '.'₹ '.$items['pricing_details']['mrp'].'</p>'; }
                                                ?>
                                            </div>
                                            <div class="order-status" id="<?php echo 'st-'.$_shipmentId; ?>">

                                                <?php 

                                                $returnstatus = $this->helper('Aceturtle\Rubicon\Helper\Order')->OrderReturnResponse($shipment['shipment_no'],$items['sku']);
                                                 if (empty($returnstatus)) {
                                                echo $this->getLayout()->createBlock("Aceturtle\Rubicon\Block\Status")->setShipmentNo($_shipmentId)->setShipmentStatus($shipment['status_name'])->setStatusType('shipment')->setTemplate("Aceturtle_Rubicon::order/status.phtml")->toHtml();
                                                 }

                                               
                                                
                                                if (!empty($returnstatus)) {
                                                    $rtstatus = $returnstatus[0]->return_status;
                                                    echo $this->getLayout()->createBlock("Aceturtle\Rubicon\Block\Status")->setShipmentNo($items['sku'])->setShipmentStatus($rtstatus)->setStatusType('return')->setTemplate("Aceturtle_Rubicon::order/status.phtml")->toHtml();
                                                }
                                                ?>
                                            </div>
                                        </div>
                                        <div class="My-account-Item-viewBtn">
                                            <button type="button" onclick="location.href='<?php echo $block->getViewUrl($_order)."sid/".$_shipmentId; ?>'"> > </button>
                                        </div>
                                    </div>
                                <?php } ?>
                            <?php } ?>
                            <?php 
                        	if(!empty($orderData)){
                            		include ($block->getTemplateFile('Aceturtle_Rubicon::order/cancellist.phtml'));
                            	}   
                            ?>
                            <!-- <div class="line-hr"></div> -->
                        </div>
                    <?php } ?>
                <?php }else { ?>
                       
                        <div class = "my-order-listingpage">
                            <div class="orderhistory-heading">
                                <?php /**<div class="col id"><?= $_order->getRealOrderId() ?></div> **/ ?>
                                <div class="col id"><? // php echo $shipment['shipment_no']; ?><?//php echo $shipment['shipment_no']; ?><p class="ordno"><span>Order No:</span>
                                <span class="orderHistoryHeadingOrderNo"><?php echo $_order->getRealOrderId(); ?></span></p></div>
                                <div class="My-account-Item-viewBtn orderHistoryHeadingBtn">
                                    <button type="button" onclick="location.href='<?php echo $block->getViewUrl($_order); ?>'"> Order Details </button>
                                </div>
                            </div>
                                <?php 
                                $orderItems = $_order->getAllItems();
				
                                foreach ($orderItems as $items) { 
				$item = $items->debug();
				if($item['product_type']!='configurable'){
				continue;
				}
				$productOptions = $items->getProductOptions();
				
				
                            $imagePath = $orderHelper->getProductImageUrl($items->getSku());
                ?>
                                    <div class="orderhistory-detail">
                                         <div class="order-image">
                                                <img src="<?php if(empty($imagePath)) { echo $placeholderImageUrl; } else { echo $imagePath; } ?>"> 
                                         </div>
                                         <div class="orderHistoryDetailWrapper">
                                            <div class="order-detail">
                                                <?php 
                                                if(!empty($items->getName())) { 
							$itemname = preg_replace('\'%20\'', ' ', $items->getName());
							 echo '<p class="productName">'.$itemname.'</p>';  
						}
						
                                                if(!empty($productOptions['attributes_info'])) { 
							foreach($productOptions['attributes_info'] as $option){
								echo '<p class="productInfo">'. $option['label'] .' :'.'<span>'.$option['value'].'</span>'.'</p>';
							 }
						}  
                                                if(!empty($items->getQtyOrdered())) { echo '<p class="productInfo">'.'Qty :'.'<span>'.number_format($items->getQtyOrdered(),0,",","").'</span>'.'</p>'; }
                                                if(!empty($items->getPrice())) { echo '<p class="productPrice">'.'Total: '.'₹ '.$items->getPrice().'</p>'; }
                                                if(!empty($items->getOriginalPrice())) { echo  '<p class="productPrice">'.'MRP: '.'₹ '.number_format($items->getOriginalPrice(),0,",","").'</p>'; } 
                                               ?>
                                            </div>
                                           
                                        </div>

					<div class="order-status">
					<?php if(!empty($orderData)){ ?>
						<strong>Cancelled</strong>
					    <?php }else { ?>
						    <strong>Pending</strong> 
					    <?php } ?>
					</div>
                                        <div class="My-account-Item-viewBtn">
                                            <!-- <button type="button" onclick="location.href='<?php echo $block->getViewUrl($_order); ?>'"> > </button> -->
                                        </div>
                                    </div>
                                <?php } ?>
                           
                            
                            <!-- <div class="line-hr"></div> -->
                        </div>
                   
                    <?php } ?>


            <?php endforeach; ?>
        </div>
    </div>
    <?php if ($shipmentCount != 0 && $block->getPagerHtml()): ?>
        <div class="order-products-toolbar toolbar bottom"><?= $block->getPagerHtml() ?></div>
    <?php endif ?>
<?php else: ?>
    <div class="message info empty"><span><?= /* @escapeNotVerified */ __('You have placed no orders.') ?></span></div>
<?php endif ?>

<style>
.orderhistory-status { display:none !important; }
</style>
