<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/** @var \Magento\Sales\Block\Order\Items $block */
?>
<div class="table-wrapper order-items">
    <div class="data table table-order-items" id="my-orders-table" summary="<?= /* @escapeNotVerified */ __('Items Ordered') ?>">
            <?php if($block->isPagerDisplayed()): ?>
                    <div  data-block="order-items-pager-top" class="order-pager-wrapper order-pager-wrapper-top">
                        <?= $block->getPagerHtml() ?>
                    </div>
               
            <?php endif ?>
           
        
        <?php $items = $block->getItems(); ?>

        <?php $giftMessage = ''?>
        <?php foreach ($items as $item): ?>
            <?php if ($item->getParentItem()) continue; ?>
                <?= $block->getItemHtml($item) ?>
                <?php if ($this->helper('Magento\GiftMessage\Helper\Message')->isMessagesAllowed('order_item', $item) && $item->getGiftMessageId()): ?>
                    <?php $giftMessage = $this->helper('Magento\GiftMessage\Helper\Message')->getGiftMessageForEntity($item); ?>
                        <div class="col options" >
                            <a href="#"
                               id="order-item-gift-message-link-<?= /* @escapeNotVerified */ $item->getId() ?>"
                               class="action show"
                               aria-controls="order-item-gift-message-<?= /* @escapeNotVerified */ $item->getId() ?>"
                               data-item-id="<?= /* @escapeNotVerified */ $item->getId() ?>">
                                <?= /* @escapeNotVerified */ __('Gift Message') ?>
                            </a>
                            <?php $giftMessage = $this->helper('Magento\GiftMessage\Helper\Message')->getGiftMessageForEntity($item); ?>
                            <div class="order-gift-message" id="order-item-gift-message-<?= /* @escapeNotVerified */ $item->getId() ?>" role="region" aria-expanded="false" tabindex="-1">
                                <a href="#"
                                   title="<?= /* @escapeNotVerified */ __('Close') ?>"
                                   aria-controls="order-item-gift-message-<?= /* @escapeNotVerified */ $item->getId() ?>"
                                   data-item-id="<?= /* @escapeNotVerified */ $item->getId() ?>"
                                   class="action close">
                                    <?= /* @escapeNotVerified */ __('Close') ?>
                                </a>
                                <dl class="item-options">
                                    <dt class="item-sender"><strong class="label"><?= /* @escapeNotVerified */ __('From') ?></strong><?= $block->escapeHtml($giftMessage->getSender()) ?></dt>
                                    <dt class="item-recipient"><strong class="label"><?= /* @escapeNotVerified */ __('To') ?></strong><?= $block->escapeHtml($giftMessage->getRecipient()) ?></dt>
                                    <dd class="item-message"><?= /* @escapeNotVerified */ $this->helper('Magento\GiftMessage\Helper\Message')->getEscapedGiftMessage($item) ?></dd>
                                </dl>
                            </div>
                        </div>
                                    <?php endif ?>
                 <?php endforeach; ?>
       
            <?php if($block->isPagerDisplayed()): ?>
                
                    <div  data-block="order-items-pager-bottom" class="order-pager-wrapper order-pager-wrapper-bottom">
                        <?= $block->getPagerHtml() ?>
                    </div>
                
            <?php endif ?>
           
       
    </div>
</div>
<?php if ($giftMessage): ?>
<script type="text/x-magento-init">
    {
        "a.action.show, a.action.close": {
            "giftMessage": {}
        }
    }
</script>
<?php endif; ?>