<?php
include($block->getTemplateFile('Aceturtle_Rubicon::order/breadcrum.phtml'));
$orderHelper = $this->helper('Aceturtle\Rubicon\Helper\Order');
?>
<?php
$objectManager   = \Magento\Framework\App\ObjectManager::getInstance();
$customerSession = $objectManager->create('Magento\Customer\Model\Session');
if ($customerSession->isLoggedIn()) {
    $customer_email   = $customerSession->getCustomer()->getEmail();
    $order_collection = $objectManager->create('Magento\Sales\Model\Order')
				->getCollection()->addAttributeToFilter('customer_email', $customer_email)
				->addAttributeToSelect('increment_id');
    if ($order_collection) {        
        $oidcount = count($order_collection);
?>
     <div class="returnHistorySection">
        <?php
	$recordCount = 0;
        foreach ($order_collection as $order_collections) {
            $orderno      = $order_collections['increment_id'];
            $returnstatus = $this->helper('Aceturtle\Rubicon\Helper\Order')->getReturnStatus($block->escapeHtml($orderno));
            if (!empty($returnstatus)) {
		$recordCount++;
                $arraycount = count($returnstatus);
                $i = 0;
                for ($i = 0; $i < $arraycount; $i++) {
                    $imagePath = $orderHelper->getProductImageUrl($returnstatus[$i]->sku);
	?>
   
		<div class="orderhistory-detail">
		    <div class="order-image">
			<?php
			 if (!empty($imagePath)) {
			?>
			   <img  style="" src="<?php echo $imagePath; ?>" style="width:200px; height:200px;">
			<?php } else { ?>
			   <img  style="" src="<?php echo $placeholderImageUrl; ?>" style="width:200px; height:200px;"> 
			<?php  } ?>
		   </div>    
		    <div class="orderHistoryDetailWrapper"> 
			<div class="order-detail"> 
			      <?php
				    $date       = $returnstatus[$i]->return_date;
				    $createDate = new DateTime($date);
				    $returndate = $createDate->format('d-m-y');
				    echo '<p class="productName">' . urldecode($returnstatus[$i]->order_item->name) . '</p>';
				    if (!empty($returnstatus[$i]->order_item->color)) {
				        echo '<p class="productInfo">' . 'Color: ' . '<span>' . $returnstatus[$i]->order_item->color . '</span>' . '</p>';
				    }
				    if (!empty($returnstatus[$i]->order_item->size)) {
				        echo '<p class="productInfo">' . 'Size: ' . '<span>' . $returnstatus[$i]->order_item->size . '</span>' . '</p>';
				    }
				    if (!empty($returnstatus[$i]->order_item->color)) {
					echo '<p class="productInfo">'.'Color: '.'<span>'.$returnstatus[$i]->order_item->color.'</span>'.'</p>';
				    }
				    echo '<p class="productPrice">'.'MRP: '.'<span>'.$returnstatus[$i]->order_item->pricing_details->mrp.'</span>'.'</p>';
				    if($returnstatus[$i]->order_item->pricing_details->price!=$returnstatus[$i]->order_item->pricing_details->mrp){
				    echo '<p class="productPrice">'.'Price: '.'<span>'.$returnstatus[$i]->order_item->pricing_details->price.'</span>'.'</p>';
				    }
				    if(!empty($returnstatus[$i]->order_item->pricing_details->item_seller_promotional_discount)){
					echo '<p class="productPrice">'.'Discounted amount: '.'<span>'.$returnstatus[$i]->order_item->pricing_details->item_seller_promotional_discount.'</span>'.'</p>';
				    }
				    
				    if(!empty($returnstatus[$i]->order_item->pricing_details->item_grand_total)){
					echo '<p class="productPrice">'.'Net Amount: '.'<span>'.$returnstatus[$i]->order_item->pricing_details->item_grand_total.'</span>'.'</p>';
				    }
	    
            
           			    echo '<p class="productInfo">'.'quantity: '.'<span>'.$returnstatus[$i]->order_item->qty_ordered.'</span>'.'</p>';
				    echo '<p class="productInfo">' . 'Order No: ' . '<span>' . $returnstatus[$i]->order_no . '</span>' . '</p>';
				    echo '<p class="productInfo">' . 'Return date: ' . '<span>' . $returndate . '</span>' . '</p>';
			      ?>
		       </div>
		    </div>
		</div>
              <?php
                }
            }
        }
	if($recordCount == 0){
		echo "<div class='message info empty'><div>  No Recode found </div></div>";
	}
    }
}
?>
</div>
