<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
$shipmentStatus  = $this->getShipmentStatus();
$shipmentNo = $this->getShipmentNo();
$statusType = $this->getStatusType();
?>
<?php
//$statusType = "shipment";
switch ($statusType) {
    case "shipment":
        $realStatus = $shipmentStatus;
        $currentStatus = 'Ordered';
        //$realStatus = "ACCEPTED";
        $statusLabels = ['Ordered','Confirmed','Shipped','Delivered'];
        $orderedStatus = ['CREATED','Created','Ordered','Created','Confirmed','To Be Allocated','Allocated','To Be Accepted'];?>
        <div id = 'placeorder-status'>
            <?php
        if(in_array($realStatus, $orderedStatus)) { $currentStatus = 'Ordered';
        ?>
       <span class= 'order-status'>Ordered</span>
         <?php } 
        $confirmedStatus = ['Manifested','Dispatched','Ready To Dispatch','Accepted','ACCEPTED','TO BE PACKED','TO BE INVOICE','To Be Invoice','Invoiced','Invoice Printed','To Be Packed','Packed','Ready To Ship'];
        if(in_array($realStatus, $confirmedStatus)) { $currentStatus = 'Confirmed';
        ?>
        <span class= 'order-status'>Confirmed</span>
         <?php } 
        $shippedStatus = ['SHIPPED','Shipped','RTO','In Transit','RTO Delivered','Lost Shipment','Handover','To Be Out For Delivery','Out For Delivery','To Be Delivered'];
        if(in_array($realStatus, $shippedStatus)) { $currentStatus = 'Shipped';
        ?>
        <span class= 'order-status'>Shipped</span>
         <?php } 
        $deliveredStatus = ['DELIVERED','Delivered','Handover Complete'];
        if(in_array($realStatus, $deliveredStatus)) { $currentStatus = 'Delivered'; 
        ?>
        <span class= 'order-status'>Delivered</span>
         <?php }?>
         </div>
         
         <?php
        $cancelStatus = ['TO BE REJECTED','Canceled'];
        if(in_array($realStatus, $cancelStatus)) { $currentStatus = 'Canceled';
        echo 'Canceled'; 
        ?>
        <span class= 'status'>STATUS: </span><span class= 'order-status'>Canceled</span>
         <?php }
        break;
        case "return":
        $realStatus = $shipmentStatus;
        $currentStatus = 'Return requested';
        $returnStatus = ['Return Requested','Return Approved','Lastmile Allocated','Refund Initiated'];
        if(in_array($realStatus, $returnStatus)) { $currentStatus = 'Return requested'; 
        ?>
        <span class= 'order-status'>Return requested</span>
         <?php }

         $returnPickedStatus = ['Return picked','Return Picked Up','Product Recieved','QC Failed','QC Pending','QC Success','To Be QC Success','Refund Requested','Initiate Refund','Refund Approved','Refund Approved','Refund Initiated'];
        if(in_array($realStatus, $returnPickedStatus)) { $currentStatus = 'Return picked'; 
        ?>
        <span class= 'order-status'>Return picked</span>
         <?php }

         $refundInitiatedStatus = ['Refund Requested','Initiate Refund','Refund Approved','Refund Approved'];
        if(in_array($realStatus, $refundInitiatedStatus)) { $currentStatus = 'Refund Initiated'; 
        ?>
        <span class= 'order-status'>Refund Initiated</span>
         <?php }

         $refundApprovedStatus = ['Refund Approved','Refund Initiated'];
        if(in_array($realStatus, $refundApprovedStatus)) { $currentStatus = 'Refund Approved'; 
        ?>
        <span class= 'order-status'>Refund Approved</span>
         <?php }

        break;
    default:
        $statusLabels = ['Ordered','Confirmed','Shipped','Delivered'];
        $currentStatus = "";
}
?>


<?php 
if($statusType=='return') { 
?>
<div class="orderhistory-status" >
    <ol class="progtrckr" data-progtrckr-steps="4">
        <li class="progtrckr-done" style="height: 150px;">
            <span>Return requested</span>
        </li>

        <li class="<?php
        if ($currentStatus == 'Return picked' || $currentStatus == 'Refund Initiated' || $currentStatus == 'Refund Approved') {
            echo 'progtrckr-done';
        } else {
            echo 'progtrckr-todo';
        }
        ?>"><span>Return picked</span>
        </li>
        <li class="<?php
        if ($currentStatus == 'Refund Initiated' || $currentStatus == 'Refund Approved') {
            echo 'progtrckr-done';
        } else {
            echo 'progtrckr-todo';
        }
        ?>" style="height: 150px;"><span>Refund Initiated</span>
        </li>
        <li class="<?php
        if ($currentStatus == 'Refund Approved' || $currentStatus == 'Refund Initiated') {
            echo 'progtrckr-done';
        } else {
            echo 'progtrckr-todo';
        }
        ?>" style="height: 150px;"><span>Refund Approved</span>
        </li>
    </ol>
</div>
<?php } ?>

<script type="text/javascript">
  require(['jquery'], function(jquery){
    jquery(document).ready(function(){
        <?php if($statusType == "return") { ?>
            jquery("#placeorder-status").hide();
        <?php }  ?>
    });
  })
</script>
