<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
use Magento\Framework\App\Action\Action;

?>
<?php
/**
 * Product list template
 *
 * @var $block \Magento\Catalog\Block\Product\ListProduct
 * @var \Magento\Framework\Escaper $escaper
 * @var \Magento\Framework\View\Helper\SecureHtmlRenderer $secureRenderer
 */
?>
<?php
$_productCollection = $block->getLoadedProductCollection();
/** @var \Magento\Catalog\Helper\Output $_helper */
$_helper = $block->getData('outputHelper');
$_imageHelper = $this->helper('Aceturtle\General\Helper\Data');
$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
$productRepository = $objectManager->get('\Magento\Catalog\Model\ProductRepository');
?>
<?php if (!$_productCollection->count()):?>
    <div class="message info empty">
        <div><?= $escaper->escapeHtml(__('We can\'t find products matching the selection.')) ?></div>
    </div>
<?php else:?>
    <div class="first-toolbar">
        <?= $block->getToolbarHtml() ?>
    </div>
    <?= $block->getAdditionalHtml() ?>
    <?php
    if ($block->getMode() == 'grid') {
        $viewMode = 'grid';
        $imageDisplayArea = 'category_page_grid';
        $showDescription = false;
        $templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::SHORT_VIEW;
    } else {
        $viewMode = 'list';
        $imageDisplayArea = 'category_page_list';
        $showDescription = true;
        $templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::FULL_VIEW;
    }
    /**
     * Position for actions regarding image size changing in vde if needed
     */
    $pos = $block->getPositioned();
    $_imgWidth = 500;
    $_imgHeight = 500;
    ?>
    <div class="products wrapper <?= /* @noEscape */ $viewMode ?> products-<?= /* @noEscape */ $viewMode ?>">
        <ol class="products list items product-items">
            <?php /** @var $_product \Magento\Catalog\Model\Product */ ?>
            <?php foreach ($_productCollection as $_product):?>
            <li class="item product product-item">
                <div data-role="add-to-links" class="actions-secondary">
                    <?php if ($addToBlock = $block->getChildBlock('addto')):?>
                        <?= $addToBlock->setProduct($_product)->getChildHtml() ?>
                    <?php endif; ?>
                </div>
                    <div class="product-item-info"
                     id="product-item-info_<?= /* @noEscape */ $_product->getId() ?>"
                     data-container="product-<?= /* @noEscape */ $viewMode ?>">
                    <?php
                    $productImage = $block->getImage($_product, $imageDisplayArea);
                    if ($pos != null) {
                        $position = 'left:' . $productImage->getWidth() . 'px;'
                            . 'top:' . $productImage->getHeight() . 'px;';
                    }
                    ?>
		  <?php // Product Image             
                         if($_product->getStyleCode()){
                            try{
                    $parentSku = $_product->getStyleCode() . "_parent";
                    $productObj = $productRepository->get($parentSku);
                    $productUrl = $productObj->getProductUrl();            
                            }catch(\Exception $error){
                                $productUrl = $_product->getProductUrl();
                            }
                         } else{
                            $productUrl = $_product->getProductUrl();
                         } 
                    ?>
                    <?php // Product Image ?>
                    <a href="<?= $escaper->escapeUrl($productUrl).'?pid='. $_product->getId(); ?>"
                       class="product photo product-item-photo"
                       tabindex="-1">
                        <?php echo  $productImage->toHtml() ?>
                        <?php $_productImage = $_product->load('media_gallery');//load media gallery attributes;
                        $_images = $_productImage->getMediaGalleryImages();
                        if($_images->count()>0):?>
                            <div class="plp-slider-wrapper">
                                <div class="plp-carousel">
                                    <?php foreach($_images as $_image): ?>                        
                                        <?php $_prodictImage = $_imageHelper->resize($_image->getFile(), $_imgWidth, $_imgHeight); ?>
                                        <img src="<?= $block->getViewURl('../images/Loader.gif') ?>"  data-src="<?= $_prodictImage ?>" max-width="<?= $_imgWidth ?>" max-height="<?= $_imgHeight ?>" alt="<?php echo $_product->getName(); ?>" />
                                   <?php endforeach; ?>
                                </div>
                            </div>
                        <?php endif;  ?>
                    </a>
                    <div class="product details product-item-details">
                        <strong class="product name product-item-name">
                            <a class="product-item-link"
                               href="<?= $escaper->escapeUrl($_product->getProductUrl()) ?>">
                                <?=/* @noEscape */ $_helper->productAttribute($_product, $_product->getName(), 'name')?>
                            </a>
                        </strong>

                        <?= /* @noEscape */ $block->getProductPrice($_product) ?>
                        <?php
                            $_productNameStripped = $block->stripTags($_product->getName(), null, true);
                        ?>
                        <?= $block->getReviewsSummaryHtml($_product, $templateType) ?>
                        <?php   if ($_product->isAvailable()):?>
                            <?= $block->getProductDetailsHtml($_product) ?>
                        <?php endif;?>
                    </div>
                </div>
            </li>
            <?php endforeach; ?>
        </ol>
    </div>
    <script>
        require(['jquery', 'js/owl.carousel'],function($){
            imagesCarousel();
            $(document).ready(imagesCarousel);
            
            function imagesCarousel() {
                $('.plp-carousel').each(function () {
                   var imageOwl = $(this);
                    $(this).owlCarousel({
                        "autoplay": true,
                        "autoplayTimeout": 1000,
                        "loop": true,
                        "items": 1,
                        "slideBy": 1,
                        "navigation" : true,
                        "pagination" : false,
                        "responsiveClass":true,
                        "dotsEach": true,
                        "nav": false
                    });
                    imageOwl.trigger('stop.owl.autoplay');
                });

                $('.product-items li.product .product-item-photo').on('mouseenter',function(e){
                   var $this = $(this).find('.plp-carousel');
                    setTimeout(function() {
                        $this.trigger('play.owl.autoplay');
                    }, 70);
                });

                $('.product-items li.product').on('mouseleave',function(e){
                   var $this = $(this).find('.plp-carousel');
                    //setTimeout(function() {
                        $this.trigger('stop.owl.autoplay');
                    // }, 10);
                });
            }

            $('body, #layer-product-list').on('contentUpdated', function () {
                imagesCarousel();
            });

        });
    </script>
<?php endif; ?>
