<?php $_product = $block->getProduct(); ?>
<?php $buttonTitle = __('Add to Cart'); ?>
<?php if ($_product->isSaleable()) : ?>
    <div class="box-tocart">
        <div class="fieldset">
            <?php if ($block->shouldRenderQuantity()) : ?>
                <div class="field qty">
                    <label class="label" for="qty"><span><?php /* @escapeNotVerified */ echo __('Qty') ?></span></label>
                    <div class="control">
                    <input type="button" class="qty-decrease-btn" id="qty-decrease" value=" - ">
                        <input 
                            type="number"
                            name="qty"
                            id="qty"
                            maxlength="12"
                            value="<?php /* @escapeNotVerified */ echo $block->getProductDefaultQty() * 1 ?>"
                            title="<?php /* @escapeNotVerified */ echo __('Qty') ?>" class="input-text qty"
                            data-validate="<?php echo $block->escapeHtml(json_encode($block->getQuantityValidators())) ?>"
                        />
                        <input type="button" class="qty-increase-btn" id="qty-incress" value=" + ">
                    </div>
                </div>
            <?php endif; ?>
            <div class="actions">
                <button
                    type="submit"
                    title="<?php /* @escapeNotVerified */ echo $buttonTitle ?>"
                    class="action primary tocart"
                    id="product-addtocart-button">
                    <span><?php /* @escapeNotVerified */ echo $buttonTitle ?></span>
                </button>
                <?php echo $block->getChildHtml('', true) ?>
            </div>
        </div>
    </div>
<?php endif; ?>
<?php if ($block->isRedirectToCartEnabled()) : ?>
    <script type="text/x-magento-init">
        {
            "#product_addtocart_form": {
                "aceturtle_quickview/catalog_product": {
                    "radioCheckboxClosest": ".nested"
                }
            }
        }
    </script>
<?php else : ?>
    <script type="text/x-magento-init">
    {
        ".actions": {
            "Aceturtle_Quickview/js/aceturtle_tocart": {
            }
        }
    }
    </script>
<?php endif; ?>

<script type="text/javascript">
    require(['jquery'], function($){ 
       $("#qty-incress").click(function(){
          var oldQty = $("#qty").val();
          var newQty = parseInt(oldQty) + 1;
          $("#qty").val(newQty);
       });
       $("#qty-decrease").click(function(){
          var oldQty = $("#qty").val();
          if(oldQty != 1) {
              var newQty = parseInt(oldQty) - 1;
              $("#qty").val(newQty);
          }
       });
    })
</script>
